# Generated by Django 5.1 on 2024-08-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content_cz', models.TextField(max_length=200, verbose_name='Краткий текст на чешском')),
                ('content_en', models.TextField(max_length=200, verbose_name='Краткий текст на английском')),
                ('pdf', models.FileField(upload_to='pdf/', verbose_name='PDF Статья')),
                ('reversed', models.BooleanField(default=False, verbose_name='Fasle-изображение слева, текст справа; True-изображение справа, текст слева')),
            ],
        ),
    ]
