# Generated by Django 5.1 on 2024-08-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_fedor_analog', '0002_alter_article_options_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
