# Generated by Django 5.1 on 2024-08-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_fedor_analog', '0003_alter_article_img_alter_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='title_cz',
            field=models.CharField(default='cz', max_length=100, verbose_name='Название на чешском'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(default='en', max_length=100, verbose_name='Название на английском'),
        ),
    ]
