# Generated by Django 5.1 on 2024-08-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_fedor_analog', '0005_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pdf',
        ),
        migrations.AddField(
            model_name='article',
            name='pdf_cz',
            field=models.FileField(default='/', upload_to='pdf/', verbose_name='PDF Статья (чешский)'),
        ),
        migrations.AddField(
            model_name='article',
            name='pdf_en',
            field=models.FileField(default='/', upload_to='pdf/', verbose_name='PDF Статья (английский)'),
        ),
    ]
